# Generated by Django 4.1.13 on 2024-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0021_propertyinfo_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinfo',
            name='property_location',
            field=models.CharField(max_length=255),
        ),
    ]
