# Generated by Django 4.1.13 on 2024-04-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0022_alter_propertyinfo_property_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
