# Generated by Django 4.1.13 on 2024-04-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0023_localisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localisation',
            name='emplacement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.propertyinfo'),
        ),
    ]
