# Generated by Django 4.1.13 on 2024-04-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0027_reviewstar'),
    ]

    operations = [
        migrations.AddField(
            model_name='localisation',
            name='property_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
