# Generated by Django 4.1.13 on 2024-05-02 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0028_localisation_property_count_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinfo',
            name='localisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.localisation'),
        ),
    ]
